## Importing libraries

In [1]:
import pandas as pd

## Reading Data

In [2]:
df= pd.read_csv("iitm_intern_train_data.csv")
test=pd.read_csv("iitm_intern_test_data.csv")

In [3]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,class
0,-0.000018,0.000043,0.000033,0.000008,0.000018,0.000168,-0.037158,-0.037202,-0.037235,-0.010982,...,-0.67649,0.96055,8.6993,-1.5021,-1.5021,-1.5017,-1.4932,-1.4933,-1.4934,10
1,-0.000001,-0.000017,-0.000091,-0.000002,-0.000005,0.000030,0.003444,0.003460,0.003551,-0.044235,...,-0.76999,6.98720,3.7207,-1.5000,-1.5000,-1.5001,-1.4996,-1.4996,-1.4996,9
2,-0.000008,0.000022,0.000273,-0.000013,0.000045,0.000235,-0.031176,-0.031198,-0.031471,-0.005473,...,-0.50284,2.72700,3.6334,-1.5067,-1.5067,-1.5068,-1.4977,-1.4978,-1.4978,10
3,-0.000003,-0.000024,-0.000068,-0.000004,-0.000014,0.000208,0.011901,0.011925,0.011993,-0.010714,...,-0.82455,5.36100,11.3180,-1.4998,-1.4998,-1.4998,-1.5001,-1.5002,-1.5000,9
4,0.000001,-0.000046,-0.000155,-0.000005,-0.000003,-0.000062,0.002543,0.002589,0.002744,-0.037649,...,-0.70297,1.80770,2.5276,-1.5059,-1.5058,-1.5055,-1.4992,-1.4992,-1.4992,9

In [4]:
test

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,1.542300e-05,2.261000e-04,0.000143,1.301300e-05,0.000024,0.000166,0.017538,0.017312,0.017169,-0.024930,...,5.3318,-0.51178,1.82140,4.4189,-1.5069,-1.5071,-1.5071,-1.4958,-1.4957,-1.4956
1,1.038100e-06,1.096700e-06,0.000007,3.286500e-06,-0.000004,-0.000024,0.016444,0.016443,0.016436,0.018125,...,5.7592,-0.60895,5.11230,3.3354,-1.4990,-1.4990,-1.4989,-1.4967,-1.4967,-1.4966
2,-3.220000e-06,-5.314800e-07,0.000009,1.214500e-06,0.000002,0.000001,0.023619,0.023619,0.023610,0.010662,...,7.7757,-0.43207,9.65110,7.3805,-1.4988,-1.4988,-1.4988,-1.4999,-1.4999,-1.4999
3,-1.619800e-05,-8.144400e-06,0.000359,-1.369800e-05,-0.000067,-0.000209,-0.105600,-0.105600,-0.105950,-0.135700,...,6.7772,-0.63783,-0.10986,3.8331,-1.4978,-1.4979,-1.4975,-1.5033,-1.5034,-1.5032
4,1.023800e-06,-1.767300e-06,-0.000006,-6.491500e-07,0.000001,-0.000005,0.067877,0.067878,0.067885,0.111340,...,5.6022,-0.50386,16.48400,5.8570,-1.4980,-1.4980,-1.4980,-1.4972,-1.4971,-1.4971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11697,-2.977800e-06,3.893700e-05,0.000024,-2.064500e-06,-0.000012,0.000093,0.050333,0.050294,0.050270,0.110870,...,13.4510,-0.75517,2.43130,6.5229,-1.4993,-1.4994,-1.4992,-1.4988,-1.4988,-1.4988
11698,-8.942900e-06,-5.281800e-06,-0.000040,-9.219800e-06,0.000108,0.000210,0.011259,0.011264,0.011304,0.030985,...,9.7128,-0.52909,1.53160,3.4815,-1.5069,-1.5069,-1.5067,-1.4979,-1.4980,-1.4980
11699,1.251300e-08,6.483100e-05,0.000136,1.481000e-05,0.000016,-0.000232,0.012924,0.012859,0.012723,-0.023308,...,2.6567,-0.67922,2.99810,10.0350,-1.4992,-1.4991,-1.4988,-1.5011,-1.5011,-1.5001
11700,-6.588600e-06,1.184400e-06,0.000008,-4.550000e-06,0.000002,-0.000012,-0.099426,-0.099428,-0.099436,-0.210730,...,4.9598,-0.61372,14.75900,3.1077,-1.4923,-1.4923,-1.4923,-1.4973,-1.4973,-1.4973
11701,-2.040800e-05,-2.185200e-05,-0.000003,3.853900e-06,0.000025,0.000122,-0.033969,-0.033947,-0.033945,-0.020829,...,14.7580,-0.80412,16.90700,11.2350,-1.5008,-1.5008,-1.5007,-1.4997,-1.4997,-1.4999

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46807 entries, 0 to 46806
Data columns (total 49 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       46807 non-null  float64
 1   1       46807 non-null  float64
 2   2       46807 non-null  float64
 3   3       46807 non-null  float64
 4   4       46807 non-null  float64
 5   5       46807 non-null  float64
 6   6       46807 non-null  float64
 7   7       46807 non-null  float64
 8   8       46807 non-null  float64
 9   9       46807 non-null  float64
 10  10      46807 non-null  float64
 11  11      46807 non-null  float64
 12  12      46807 non-null  float64
 13  13      46807 non-null  float64
 14  14      46807 non-null  float64
 15  15      46807 non-null  float64
 16  16      46807 non-null  float64
 17  17      46807 non-null  float64
 18  18      46807 non-null  float64
 19  19      46807 non-null  float64
 20  20      46807 non-null  float64
 21  21      46807 non-null  float64
 22  22      46807 non-null  float64
 23  23      46807 non-null  float64
 24  24      46807 non-null  float64
 25  25      46807 non-null  float64
 26  26      46807 non-null  float64
 27  27      46807 non-null  float64
 28  28      46807 non-null  float64
 29  29      46807 non-null  float64
 30  30      46807 non-null  float64
 31  31      46807 non-null  float64
 32  32      46807 non-null  float64
 33  33      46807 non-null  float64
 34  34      46807 non-null  float64
 35  35      46807 non-null  float64
 36  36      46807 non-null  float64
 37  37      46807 non-null  float64
 38  38      46807 non-null  float64
 39  39      46807 non-null  float64
 40  40      46807 non-null  float64
 41  41      46807 non-null  float64
 42  42      46807 non-null  float64
 43  43      46807 non-null  float64
 44  44      46807 non-null  float64
 45  45      46807 non-null  float64
 46  46      46807 non-null  float64
 47  47      46807 non-null  float64
 48  class   46807 non-null  int64
dtypes: float64(48), int64(1)
memory usage: 17.5 MB

### Analizing data

In [6]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,class
count,46807.000000,4.680700e+04,4.680700e+04,46807.000000,4.680700e+04,4.680700e+04,46807.000000,46807.000000,46807.000000,46807.000000,...,46807.000000,46807.000000,46807.000000,46807.000000,46807.000000,46807.000000,46807.000000,46807.000000,46807.000000,46807.000000
mean,-0.000003,1.415116e-06,9.925226e-07,-0.000001,1.207948e-06,-7.075103e-07,0.001882,0.001881,0.001880,-0.011906,...,-0.337555,7.300926,8.271516,-1.500881,-1.500905,-1.500799,-1.497778,-1.497800,-1.497692,6.014357
std,0.000080,5.869695e-05,2.372014e-04,0.000070,6.013258e-05,2.278823e-04,0.036524,0.036521,0.036526,0.066422,...,27.964812,12.600663,6.583845,0.003661,0.003671,0.003635,0.003176,0.003176,0.003187,3.156842
min,-0.013721,-5.414400e-03,-1.358000e-02,-0.012787,-8.355900e-03,-9.741300e-03,-0.139890,-0.135940,-0.130860,-0.218640,...,-0.902350,-0.596830,0.320660,-1.525500,-1.526200,-1.523700,-1.521400,-1.523200,-1.521300,1.000000
25%,-0.000007,-1.442100e-05,-7.270050e-05,-0.000005,-1.499750e-05,-7.455400e-05,-0.019870,-0.019911,-0.019887,-0.032113,...,-0.715590,1.452650,4.437100,-1.503300,-1.503400,-1.503200,-1.499600,-1.499600,-1.499600,3.000000
50%,-0.000003,8.966400e-07,4.999900e-07,-0.000001,6.887400e-07,-3.926500e-07,0.013179,0.013185,0.013200,-0.015464,...,-0.661920,3.310100,6.463100,-1.500300,-1.500300,-1.500300,-1.498100,-1.498100,-1.498000,6.000000
75%,0.000002,1.884650e-05,7.459750e-05,0.000004,1.886350e-05,7.077650e-05,0.024758,0.024763,0.024766,0.020449,...,-0.573910,8.289450,9.861250,-1.498200,-1.498200,-1.498200,-1.496200,-1.496300,-1.496200,9.000000
max,0.005784,4.525300e-03,3.330400e-03,0.001453,8.245100e-04,2.753600e-03,0.069125,0.069130,0.069131,0.352580,...,3670.800000,889.930000,153.150000,-1.457600,-1.456100,-1.455500,-1.337200,-1.337200,-1.337100,11.000000

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop("class", axis=1),df['class'],test_size=0.20)

In [8]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
29109,4.097600e-06,7.238200e-05,-1.130400e-04,-1.172400e-05,4.600700e-05,-0.000361,0.020443,0.020371,0.020484,-0.032592,...,3.8681,-0.67531,6.27930,7.6790,-1.5094,-1.5094,-1.5094,-1.4966,-1.4967,-1.4968
24038,1.226900e-06,7.424900e-07,-1.757400e-07,3.122800e-06,-8.311400e-07,0.000014,0.025811,0.025811,0.025811,0.047470,...,6.8042,-0.47717,9.22940,14.0370,-1.4984,-1.4984,-1.4984,-1.4981,-1.4981,-1.4981
4572,6.357100e-07,-3.696700e-05,1.189300e-04,4.648800e-06,1.358400e-05,0.000264,0.026847,0.026884,0.026765,0.083557,...,2.5855,-0.64979,0.94398,7.5306,-1.5029,-1.5031,-1.5030,-1.5024,-1.5024,-1.5026
16569,-1.007300e-05,3.491700e-05,3.560900e-04,1.676200e-06,1.657500e-05,-0.000105,0.008263,0.008228,0.007872,-0.000244,...,5.1777,-0.73799,0.02836,4.4329,-1.5074,-1.5074,-1.5062,-1.4963,-1.4963,-1.4962
15825,2.056700e-07,2.250100e-07,-9.118800e-06,-3.214600e-07,6.069300e-07,-0.000005,0.028514,0.028514,0.028523,-0.002635,...,3.9705,-0.57495,12.73700,6.9050,-1.4968,-1.4968,-1.4968,-1.4968,-1.4968,-1.4968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32583,-9.118000e-06,-4.483000e-05,6.654000e-05,-9.255100e-06,-1.321300e-05,0.000024,0.038276,0.038321,0.038254,0.011687,...,4.1936,-0.77892,14.32700,15.3820,-1.4997,-1.4998,-1.4998,-1.4999,-1.4999,-1.4999
37069,-1.298500e-05,-4.160500e-05,2.960700e-04,5.898000e-06,-9.719300e-05,0.000009,-0.125270,-0.125230,-0.125530,-0.143670,...,4.6918,-0.74271,1.57780,9.9241,-1.4972,-1.4973,-1.4971,-1.4999,-1.5000,-1.4996
10558,-1.055000e-05,-4.572900e-05,-1.184500e-04,1.577600e-05,7.691400e-06,-0.000092,-0.025210,-0.025165,-0.025046,-0.021633,...,2.8603,-0.69770,3.23170,3.4722,-1.5075,-1.5075,-1.5071,-1.4972,-1.4973,-1.4970
34708,4.368500e-07,-4.176600e-07,6.499100e-06,-2.568300e-06,-4.696200e-06,-0.000001,0.062087,0.062087,0.062081,0.108830,...,10.1660,-0.47820,9.92980,4.9552,-1.4977,-1.4977,-1.4977,-1.4992,-1.4992,-1.4991
10040,-9.976300e-06,2.345600e-05,3.165500e-05,-2.724500e-06,-8.908600e-06,0.000057,-0.040201,-0.040225,-0.040256,-0.029904,...,4.3810,-0.72222,2.78400,3.4688,-1.4987,-1.4987,-1.4990,-1.5051,-1.5052,-1.5052

### Preprocessing the data

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)### Preprocessing the data

StandardScaler()

In [10]:
scaled_features = scaler.transform(X_train)
scaled_valid = scaler.transform(X_test)
scaled_test = scaler.transform(test)

In [11]:
scaled_features

array([[ 0.09472204,  1.29621466, -0.48001676, ...,  0.36903492,
         0.34440156,  0.27810462],
       [ 0.05776821, -0.01587801, -0.00467638, ..., -0.10227139,
        -0.09540334, -0.12904105],
       [ 0.05015796, -0.70653525,  0.49695067, ..., -1.45334949,
        -1.44623268, -1.53839145],
       ...,
       [-0.09383299, -0.86701312, -0.50280157, ...,  0.18051239,
         0.15591374,  0.21546682],
       [ 0.04759809, -0.03712641,  0.02343545, ..., -0.44789602,
        -0.44096434, -0.44223003],
       [-0.08644789,  0.40012469,  0.12938231, ..., -2.30170085,
        -2.32584248, -2.35268279]])

In [12]:
df_train = pd.DataFrame(scaled_features,columns=df.columns[:-1])
df_val = pd.DataFrame(scaled_valid,columns=df.columns[:-1])
df_test = pd.DataFrame(scaled_test,columns=df.columns[:-1])
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,0.094722,1.296215,-0.480017,-0.907334,1.120611,-1.650160,0.508630,0.506719,0.509792,-0.314594,...,-0.667766,-0.010892,-0.079543,-0.087706,-2.333082,-2.320592,-2.372619,0.369035,0.344402,0.278105
1,0.057768,-0.015878,-0.004676,0.341931,-0.059910,0.064039,0.656186,0.656262,0.656211,0.893205,...,-0.237726,-0.003288,0.152006,0.886070,0.681607,0.686568,0.664166,-0.102271,-0.095403,-0.129041
2,0.050158,-0.706535,0.496951,0.470334,0.303413,1.209197,0.684664,0.685758,0.682433,1.437606,...,-0.855623,-0.009912,-0.498306,-0.110435,-0.551675,-0.598310,-0.605762,-1.453349,-1.446233,-1.538391
3,-0.087693,0.610035,1.495776,0.220209,0.378799,-0.480458,0.173834,0.172925,0.163146,0.173399,...,-0.475953,-0.013297,-0.570172,-0.584871,-1.784956,-1.773836,-1.489191,0.463296,0.470060,0.466018
4,0.044622,-0.025356,-0.042341,0.052118,-0.023664,-0.022665,0.730487,0.730566,0.730754,0.137336,...,-0.652768,-0.007040,0.427313,-0.206250,1.120107,1.123973,1.105880,0.306194,0.312987,0.278105

### Using grid search to find the optimum value of parameters. here in SVC I took as C , Kernel and Gamma as parameters

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
svm_model = SVC()

In [15]:
parameters = {"C":[0.1,0.7,1,5,10,30],"kernel":["rbf"],"gamma":[0.0001,0.001,0.01,0.1,1,10]}
gs = GridSearchCV(svm_model, parameters, n_jobs=-1)
gs.fit(df_train, y_train)

GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 0.7, 1, 5, 10, 30],
                         'gamma': [0.0001, 0.001, 0.01, 0.1, 1, 10],
                         'kernel': ['rbf']})

In [16]:
#to get optimum parameters
gs.best_params_

{'C': 30, 'gamma': 0.01, 'kernel': 'rbf'}

Trained the SVC model using the optimum parameters got from Grid search to get the best presiction

In [15]:
svm_model=SVC(C=30,gamma=0.01,kernel='rbf')
svm_model.fit(df_train,y_train)
pred_svm = svm_model.predict(df_val)

In [21]:
from sklearn.metrics import accuracy_score, mean_squared_error

In [22]:
mean_squared_error(y_test,pred_svm)

0.6161076693014313

## got the accuracy score of 98% which is better than knn

In [18]:
print(accuracy_score(y_test,pred_svm))

0.9848323007904294

In [19]:
y_pred = svm_model.predict(df_train)

In [21]:
print(accuracy_score(y_train, y_pred))

0.992522366137001

In [22]:
pred_submission = svm_model.predict(df_test)

In [31]:
test['class'] = pred_submission

In [34]:
pred_submission

array([ 1,  5,  5, ...,  6, 11, 10], dtype=int64)

In [33]:
test

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,class
0,1.542300e-05,2.261000e-04,0.000143,1.301300e-05,0.000024,0.000166,0.017538,0.017312,0.017169,-0.024930,...,-0.51178,1.82140,4.4189,-1.5069,-1.5071,-1.5071,-1.4958,-1.4957,-1.4956,1
1,1.038100e-06,1.096700e-06,0.000007,3.286500e-06,-0.000004,-0.000024,0.016444,0.016443,0.016436,0.018125,...,-0.60895,5.11230,3.3354,-1.4990,-1.4990,-1.4989,-1.4967,-1.4967,-1.4966,5
2,-3.220000e-06,-5.314800e-07,0.000009,1.214500e-06,0.000002,0.000001,0.023619,0.023619,0.023610,0.010662,...,-0.43207,9.65110,7.3805,-1.4988,-1.4988,-1.4988,-1.4999,-1.4999,-1.4999,5
3,-1.619800e-05,-8.144400e-06,0.000359,-1.369800e-05,-0.000067,-0.000209,-0.105600,-0.105600,-0.105950,-0.135700,...,-0.63783,-0.10986,3.8331,-1.4978,-1.4979,-1.4975,-1.5033,-1.5034,-1.5032,11
4,1.023800e-06,-1.767300e-06,-0.000006,-6.491500e-07,0.000001,-0.000005,0.067877,0.067878,0.067885,0.111340,...,-0.50386,16.48400,5.8570,-1.4980,-1.4980,-1.4980,-1.4972,-1.4971,-1.4971,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11697,-2.977800e-06,3.893700e-05,0.000024,-2.064500e-06,-0.000012,0.000093,0.050333,0.050294,0.050270,0.110870,...,-0.75517,2.43130,6.5229,-1.4993,-1.4994,-1.4992,-1.4988,-1.4988,-1.4988,7
11698,-8.942900e-06,-5.281800e-06,-0.000040,-9.219800e-06,0.000108,0.000210,0.011259,0.011264,0.011304,0.030985,...,-0.52909,1.53160,3.4815,-1.5069,-1.5069,-1.5067,-1.4979,-1.4980,-1.4980,5
11699,1.251300e-08,6.483100e-05,0.000136,1.481000e-05,0.000016,-0.000232,0.012924,0.012859,0.012723,-0.023308,...,-0.67922,2.99810,10.0350,-1.4992,-1.4991,-1.4988,-1.5011,-1.5011,-1.5001,6
11700,-6.588600e-06,1.184400e-06,0.000008,-4.550000e-06,0.000002,-0.000012,-0.099426,-0.099428,-0.099436,-0.210730,...,-0.61372,14.75900,3.1077,-1.4923,-1.4923,-1.4923,-1.4973,-1.4973,-1.4973,11
11701,-2.040800e-05,-2.185200e-05,-0.000003,3.853900e-06,0.000025,0.000122,-0.033969,-0.033947,-0.033945,-0.020829,...,-0.80412,16.90700,11.2350,-1.5008,-1.5008,-1.5007,-1.4997,-1.4997,-1.4999,10

In [35]:
test.to_csv("NA20B041_SAAD_predictions.csv",index=False)